// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjnfjptljzxsowotmmsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqbmZqcHRsanp4c293b3RtbXN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5MjM2ODksImV4cCI6MjA0OTQ5OTY4OX0.rQ1p4ud5xmsQPl0uejqv9qMN69z5czthr5vqjN_9TVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);